In [47]:
#import sklearn, re
import pandas
import numpy as np

#read data csv
expression_data = pandas.read_csv("GSE89843_TEP_Count_Matrix.txt", header=0, sep=" ")
expression_data = expression_data.iloc[:,1:].T

patient_data = pandas.read_csv("PatientData.csv", header=0, sep="\t")
patient_group = patient_data.loc[:,["GEO ID (GSE89843)", "Classification group"]]
patient_group.set_index("GEO ID (GSE89843)", inplace=True)

merged_data = pandas.concat([expression_data, patient_group], axis=1, join="inner")
recoded_y = [1 if i == "NSCLC" else 0 for i in merged_data["Classification group"]]
merged_data.drop(columns=["Classification group"], inplace=True)

in_data = merged_data.to_numpy()
out_data = np.array(recoded_y)

#test-train split
#fit random forest
#evaluate random forest

[[ 12 116  68 ...  70  39   0]
 [  0  25  19 ...  70  34   0]
 [ 72  56  21 ...  35  42   0]
 ...
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   3]
 [  7   5   1 ...   0   0   0]]
